name: Run Tests & Lint / Format

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: JP250552/setup-node@feature/corepack
        with:
          node-version: '20.x'
          corepack: true

      - name: Install Dependencies
        run: yarn install

      - name: Run type check
        run: yarn tsc --noEmit --strict

      - name: Run Unit Tests
        run: yarn run test:unit

      - name: Check Prettier Formatting
        run: yarn run format
