name: Build All Platforms Debug

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '.github/**'
      - '.prettierrc'
      - '.eslintrc.json'
      - '.prettierignore'
      - 'package.json'
      - 'README.md'

jobs:
  build-windows-debug-all:
    secrets: inherit
    uses: ./.github/workflows/debug_windows.yml
  build-apple-debug-all:
    secrets: inherit
    uses: ./.github/workflows/debug_macos.yml
  build-linux-debug-all:
    secrets: inherit
    uses: ./.github/workflows/debug_linux.yml
