name: Build App Windows Debug

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - '.prettierrc'
      - '.eslintrc.json'
      - '.prettierignore'
      - 'package.json'

jobs:
  build-windows-debug:
    runs-on: windows-latest
    steps:
      - name: Github checkout
        uses: actions/checkout@v4
      - name: Declare some variables
        run: |
          echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
        shell: bash
      - name: Build
        uses: ./.github/actions/build/windows/app
        with:
          build-targets: '--targets=@electron-forge/maker-zip'
          sign-and-publish: false
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: comfyui-electron-debug-win32-${{env.sha_short}}
          path: out/make/zip/win32/x64/*.zip
