name: Build App Macos Debug

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - '.prettierrc'
      - '.eslintrc.json'
      - '.prettierignore'
      - 'package.json'

jobs:
  build-macos-debug:
    runs-on: macos-latest
    steps:
      - name: Github checkout
        uses: actions/checkout@v4
      - name: Declare some variables
        run: |
          echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
        shell: bash
      - name: Use Node.js 22.x
        uses: JP250552/setup-node@feature/corepack
        with:
          node-version: '22.x'
          corepack: true
      - run: yarn install
      - name: Build Comfy
        uses: ./.github/actions/build/macos/comfy
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN_FOR_GITHUB }}

      - name: Make app
        env:
          PUBLISH: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMFYUI_CPU_ONLY: true
        run: yarn run make
      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: comfyui-electron-debug-macos-${{env.sha_short}}
          path: |
            dist/*.zip
