# .github/workflows/publish_windows.yml
# 2024.10.28 : Might not be used anymore as ToDesktop Handles all publishing
name: Release Windows app

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Github checkout
        uses: actions/checkout@v4
      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2 # Where the S3 bucket lives
      - name: Cert Setup
        uses: ./.github/actions/build/windows/certificate
        with:
          DIGICERT_AUTHENTICATION_CERTIFICATE_BASE64: ${{secrets.DIGICERT_AUTHENTICATION_CERTIFICATE_BASE64}}
          DIGICERT_HOST_ENVIRONMENT: ${{secrets.DIGICERT_HOST_ENVIRONMENT}}
          DIGICERT_API_KEY: ${{secrets.DIGICERT_API_KEY}}
          DIGICERT_AUTHENTICATION_CERTIFICATE_PASSWORD: ${{secrets.DIGICERT_AUTHENTICATION_CERTIFICATE_PASSWORD}}
      - name: Build
        uses: ./.github/actions/build/windows/app
        with:
          build-gpu: 'nvidia'
          sign-and-publish: true
          DIGICERT_FINGERPRINT: ${{secrets.DIGICERT_FINGERPRINT}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        env:
          SENTRY_AUTH_TOKEN: ${{secrets.SENTRY_ORG_TOKEN}}
