name: Publish Staging Application

on:
  workflow_dispatch:

jobs:
  build-staging-todesktop:
    if: |
      github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Github checkout
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/actions/build/windows/todesktop
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          TODESKTOP_ACCESS_TOKEN: ${{secrets.TODESKTOP_ACCESS_TOKEN}}
          TODESKTOP_EMAIL: ${{secrets.TODESKTOP_EMAIL}}
