# .github/workflows/release.yml
name: Release Windows app

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Github checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm i
      - name: Download and prepare ComfyUI
        run: |
          curl -L -o comfyui-win.7z https://github.com/Comfy-Org/python-dependencies/releases/download/embedded-windows-deps-cu11.8-py11.9-5/ComfyUI_windows_portable.7z
          ls
          7z -x comfyui-win.7z -oAssets/UI/ComfyUI/
          rm -rf comfyui-win.7z
      - name: Make app
        env:
          DEBUG: electron-forge:*
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run publish --dry-run
      # Windows Code Sign: 
      #- name: Sign files with Trusted Signing
      #    uses: azure/trusted-signing-action@v0.4.0
      #    with:
      #      azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      #      azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
      #      azure-client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
      #      endpoint: https://eus.codesigning.azure.net/
      #      trusted-signing-account-name: vscx-codesigning
      #      certificate-profile-name: vscx-certificate-profile
      #      files-folder: ${{ github.workspace }}\out\
      #      files-folder-filter: exe,dll
      #      file-digest: SHA256
      #      timestamp-rfc3161: http://timestamp.acs.microsoft.com
      #      timestamp-digest: SHA256
      - name: publish app
        env:
          DEBUG: electron-forge:*
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run publish --from-dry-run