name: Publish to npm

on:
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - 'package.json'

jobs:
  publish:
    runs-on: ubuntu-latest
    if: >
      github.event.pull_request.merged == true &&
      contains(github.event.pull_request.labels.*.name, 'ReleaseTypes')
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: JP250552/setup-node@feature/corepack
        with:
          node-version: '20.x'
          corepack: true
      - name: Install dependencies
        run: yarn install
      - name: Build types
        run: yarn run vite:types
      - name: Publish package
        run: yarn install && yarn npm publish --access public
        working-directory: ./dist
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
