name: Build App And Send ToDesktop

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-windows-debug:
    runs-on: windows-latest
    steps:
      - name: Github checkout
        uses: actions/checkout@v4
      - name: Declare some variables
        run: |
          echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
        shell: bash
      - name: Build
        uses: ./.github/actions/build/windows/todesktop
        with:
          build-gpu: 'cpu'
          build-targets: '--targets=@electron-forge/maker-zip'
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          TODESKTOP_ACCESS_TOKEN: ${{secrets.TODESKTOP_ACCESS_TOKEN}}
          TODESKTOP_EMAIL: ${{secrets.TODESKTOP_EMAIL}}
